=== LeeBergstrand/NCBI_Tools/src/sra/sdk/services/fuse/sra-fuser.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="TAR">
    <xs:annotation>
      <xs:documentation>This could be used to create an automatic tar archive within directory specified by a physical Directory node in main fuse.xml file.</xs:documentation>
    </xs:annotation>
  </xs:element>
        
  <xs:element name="FUSE">
    <xs:annotation>
      <xs:documentation>Main sra-fuser virtual directory structure root.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="AllEntries">
          <xs:sequence>
            <xs:element name="TAR" type="TARType" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
  
  <xs:complexType name="AllEntries">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="Directory" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:complexContent>
            <xs:extension base="DirectoryType"/>
          </xs:complexContent>
        </xs:complexType>
      </xs:element>
      <xs:element name="File" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:complexContent>
            <xs:extension base="FileType"/>
          </xs:complexContent>
        </xs:complexType>
      </xs:element>
      <xs:element name="SRA" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:complexContent>
            <xs:extension base="SRAType"/>
          </xs:complexContent>
        </xs:complexType>
      </xs:element>
      <xs:element name="SRAConfig" minOccurs="0" maxOccurs="1">
        <xs:complexType>
          <xs:complexContent>
            <xs:extension base="SRAConfigType"/>
          </xs:complexContent>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="DirectoryType">
    <xs:annotation>
      <xs:documentation>If Directory has path attribute it will detect presence of *.tar.xml files 
                        with root node TAR (see above) and automatically create .tar file out of detect file's content.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="AllEntries">
        <xs:sequence>
          <xs:element name="TAR" type="TARType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute ref="name" use="optional" >
          <xs:annotation>
            <xs:documentation>Must have name OR path, or both</xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute name="path" type="xs:anyURI" use="optional">
          <xs:annotation>
            <xs:documentation>absolute or relative path to a physical directory</xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute ref="timestamp" use="optional"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="FileType">
    <xs:attribute ref="name" use="optional" >
      <xs:annotation>
        <xs:documentation>May be used to override original file name in path</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="path" type="xs:anyURI" use="required">
      <xs:annotation>
        <xs:documentation>absolute or relative path to a file</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute ref="timestamp" use="optional" />
    <xs:attribute name="password" type="xs:string" use="optional" />
  </xs:complexType>

  <xs:complexType name="SRAType">
    <xs:attribute name="accession" use="required" type="xs:NCName" >
      <xs:annotation>
        <xs:documentation>SRA accession used to open the run</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="path" type="xs:anyURI" use="optional">
      <xs:annotation>
        <xs:documentation>path is used for direct opening of the tables, for automatic search do not specify</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <!-- next 5 attributes must always come together if present -->
    <xs:attribute ref="timestamp" use="optional">
      <xs:annotation>
        <xs:documentation>time stamp of the size/md5 attribute values</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="size.sra" type ="xs:nonNegativeInteger" use="optional">
      <xs:annotation>
        <xs:documentation>file size in bytes</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="md5.sra" type ="xs:hexBinary" use="optional">
      <xs:annotation>
        <xs:documentation>MD5 sum of the file</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="size.lite.sra" type ="xs:nonNegativeInteger" use="optional">
      <xs:annotation>
        <xs:documentation>file size in bytes</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="md5.lite.sra" type ="xs:hexBinary" use="optional">
      <xs:annotation>
        <xs:documentation>MD5 sum of the file</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="SRAConfigType">
    <xs:complexContent>
      <xs:extension base="AllEntries">
        <xs:annotation>
          <xs:documentation>Initially all attributes are TRUE, as first config node is encountered only attributes set to TRUE in THAT node are active all others become FALSE</xs:documentation>
        </xs:annotation>
        <xs:attribute name="run-directory" type="xs:boolean" use="optional" default="false" >
          <xs:annotation>
            <xs:documentation>Create run directory for the SRA node</xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute name="SRA-archive" type="xs:boolean" use="optional" default="false" />
        <xs:attribute name="SRA-archive-lite" type="xs:boolean" use="optional" default="false" />
        <xs:attribute name="fastq" type="xs:boolean" use="optional" default="false" /> 
        <xs:attribute name="SFF" type="xs:boolean" use="optional" default="false" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="TARType">
    <xs:complexContent>
      <xs:extension base="TARItemList">
        <xs:attribute ref="name" use="required">
          <xs:annotation>
            <xs:documentation>Ignored in dynamically loaded .tar.xml files, .tar.xml file name is used, ex: data5.tar.xml -> data5.tar</xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="TARItem">
    <xs:attribute name="name" type="xs:anyURI" use="optional" >
      <xs:annotation>
        <xs:documentation>Cannot start with '/'. If omitted, portion of path after last '/' is used</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="path" type="xs:anyURI" use="required">
      <xs:annotation>
        <xs:documentation>Absolute or relative path to a file. In case of automatic tar relative
                          paths will be resolved to from directory where .tar.xml is located.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute ref="timestamp" use="optional"/>
    <xs:attribute name="size" use="required" type="xs:nonNegativeInteger">
      <xs:annotation>
        <xs:documentation>Actual file size is required to pre-calc resulting file .tar size</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="executable" type="xs:boolean" use="optional" default="false">
        <xs:annotation>
            <xs:documentation>Indicate if files has executable type</xs:documentation>
        </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="TARItemList">
      <xs:sequence>
        <xs:element name="Item" type="TARItem" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
  </xs:complexType>
  
  <xs:attribute name="name" type="xs:NCName"/>
  
  <xs:attribute name="timestamp" type="xs:dateTime">
    <xs:annotation>
      <xs:documentation>Sets timestamp on a node formatted: YYYY-MM-DDTHH:MM:SS</xs:documentation>
    </xs:annotation>
  </xs:attribute>
  
</xs:schema>

=== LeeBergstrand/NCBI_Tools/src/sra/sdk/services/fuse/test/fuse-dir.xml
<?xml version="1.0" encoding="UTF-8"?>
<FUSE xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/P:\asm-trace\v2\src\services\fuse/sra-fuser.xsd">
    <!-- all text nodes are ignored -->
        
    <Directory name="md5">
        <SRA accession="SRR036971" />
        <SRA accession="SRR036978" />
        <SRA accession="SRR036982" />
        <SRA accession="SRR036989" />
        <SRA accession="SRR037013" />
        <SRA accession="SRR037031" />
        <SRA accession="SRR037032" />
        <SRA accession="SRR037033" 
             timestamp="2012-01-01T12:30:45" size.sra="12312312" md5.sra="161dcff775546383c8d87a05ce473897"
                      size.lite.sra="45666" md5.lite.sra="788b956e2b897afb6d2dcfd30b568653" />
    </Directory>
    
    
    <Directory name="Direct" path="/net/snowman/vol/export2/dweb_priv/staff/golikov" />
    <Directory name="EmptyLink" path="/home/golikov/work/web" />
    <Directory name="SRR027555.direct" path="/panfs/pan1.be-md.ncbi.nlm.nih.gov/sra-test/golikov/fuse/indexed/SRR/000026/SRR027555" />
    <Directory name="NotEmptyLink" path="/home/golikov/work/web" >
        <Directory name="xsl">
            <File name="LinkFile" path="/panfs/pan1.be-md.ncbi.nlm.nih.gov/sra-test/golikov/fuse/fuse-dir.xml" />
            <File name="PlainFile" path="./fuse-dir.xml" />
            <SRA accession="SRR001334" />
            <SRA accession="SRR027555" path="/panfs/pan1.be-md.ncbi.nlm.nih.gov/sra-test/golikov/fuse/indexed/SRR/000026/SRR027555"/>
            <SRA accession="SRR035305" path="/panfs/pan1/trace-flatten/klymenka/sra-makeidx/SRR035305"/>
            <SRA accession="SRR038603" />
            <SRA accession="SRR037032" />
            <Directory name="ts2002-10-21-20-00-00" timestamp="2002-10-21T20:00:00" path="/home/golikov/work/fuse-2.5.3" />
        </Directory>
    </Directory>
    <Directory name="EmptyDir"  timestamp="2020-10-21T20:00:00"/>
    <File name="SomeFile" path="ls.txt" />
    <File name="LinkFile" path="fuse-dir.xml" />
    <File name="FIFOFile" path="/panfs/pan1.be-md.ncbi.nlm.nih.gov/sra-test/golikov/fuse/fifo" />
    <File name="FIFOLink" path="/panfs/pan1.be-md.ncbi.nlm.nih.gov/sra-test/golikov/fuse/fifo.lnk" />
    <Directory name="KarRuns">
  	   <SRA accession="SRR027555" path="SRR027555.sra" />
  	   <SRA accession="SRR027555l" path="SRR027555.lite.sra" />
  	   <Directory name="KarRunsDup">
  	     <SRA accession="SRR027555" path="SRR027555.sra" />
  	     <SRA accession="SRR027555x" path="SRR027555.lite.sra" />
  	   </Directory>
    </Directory>
    <Directory name="tar-auto" path="tar-test">
    </Directory>
    
    <Directory name="dir-w-tar1">
    <Directory name="dir-w-tar2">
    <Directory name="dir-w-tar3">
    <Directory name="dir-w-tar4">
    <TAR name="inline.tar">
        <Item name="list" path="ls.txt" size="697" timestamp="1980-01-31T20:22:03"/>
        <Item path="ls.txt" size="697" executable="false" />
        <Item name="fastq-validator.pl" path="fastq-validator.pl" size="907" executable="true" />
        <Item name="fastq-validator-abs.pl" path="/panfs/pan1.be-md.ncbi.nlm.nih.gov/sra-test/golikov/fuse/fastq-validator.pl" size="907" executable="true"/>

<Item size ="71999284" path="tar-files/eclipse-cpp-ganymede-SR2-win32.zip" />
<Item size ="145997460" path="tar-files/eclipse-php-galileo-win32.zip" />
<Item size ="126641337" path="tar-files/mysql-noinstall-5.1.37-win32.zip" />
<Item size ="51459616" path="tar-files/xampplite-win32-1.7.1.zip" />


    </TAR>
    </Directory>
    </Directory>
    </Directory>
    </Directory>
</FUSE>
