=== LeeBergstrand/NCBI_Tools/src/serial/datatool/testdata/elink.dtd
<!ELEMENT        ERROR          (#PCDATA)>	<!-- .+ -->
<!ELEMENT        Info           (#PCDATA)>	<!-- .+ -->

<!ELEMENT	Id		(#PCDATA)>	<!-- \d+ -->
<!ATTLIST	Id		
			HasLinkOut  (Y|N)	#IMPLIED	
			HasNeighbor (Y|N)	#IMPLIED
			>
			
<!ELEMENT	Score		(#PCDATA)>	<!-- \d+ -->
<!ELEMENT	DbFrom		(#PCDATA)>	<!-- \S+ -->
<!ELEMENT	DbTo		(#PCDATA)>	<!-- \S+ -->
<!ELEMENT	LinkName	(#PCDATA)>	<!-- \S+ -->

<!ELEMENT	IdList		(Id*)>

<!-- cmd=neighbor -->
<!ELEMENT	Link		(Id, Score?)>

<!ELEMENT	LinkSetDb	(DbTo, LinkName, (Link*|Info), ERROR?)>

<!-- cmd=links -->

<!ELEMENT	Url		(#PCDATA)>	<!-- \S+ -->
<!ELEMENT       SubjectType	(#PCDATA)>	<!-- .+ -->
<!ELEMENT       ProviderName	(#PCDATA)>	<!-- .+ -->
<!ELEMENT       ProviderNameAbbr	(#PCDATA)>	<!-- \S+ -->
<!ELEMENT       ProviderId	(#PCDATA)>	<!-- \d+ -->		

<!ELEMENT	ObjUrl	(
				Url,
                                SubjectType,
                                ProviderName,
                                ProviderNameAbbr,
                                ProviderId			
			)>

<!ELEMENT	IdUrlSet	(Id,(ObjUrl+|Info))>

<!ELEMENT	IdUrlList	(IdUrlSet*,ERROR?)>


<!-- cmd=ncheck & lcheck -->
<!ELEMENT	IdCheckList	(Id*,ERROR?)>


<!-- Common -->
<!ELEMENT	LinkSet		(DbFrom, 
				((IdList?, LinkSetDb*) | IdUrlList | IdCheckList | ERROR)  
				)>

<!ELEMENT	eLinkResult	(LinkSet+,ERROR?)>

=== LeeBergstrand/NCBI_Tools/src/serial/datatool/testdata/data/elink.xml
<?xml version="1.0"?>
<!DOCTYPE eLinkResult PUBLIC "-//NCBI//elink/EN" "elink.dtd">
<eLinkResult>
  <LinkSet>
    <DbFrom>taxonomy</DbFrom>
    <IdUrlList>
      <IdUrlSet>
        <Id>9606</Id>
        <ObjUrl>
          <Url>http://www.ncbi.nlm.nih.gov/genome/guide/H_sapiens.html</Url>
          <SubjectType>organism-specific</SubjectType>
          <ProviderName>NCBI Genome Guide</ProviderName>
          <ProviderNameAbbr>ncbigg</ProviderNameAbbr>
          <ProviderId>3218</ProviderId>
        </ObjUrl>
        <ObjUrl>
          <Url>http://genome.ucsc.edu/cgi-bin/hgGateway?db=hg11</Url>
          <SubjectType>sequence screening/similarity/alignment</SubjectType>
          <ProviderName>UCSC Genome Browser</ProviderName>
          <ProviderNameAbbr>UCSCgb</ProviderNameAbbr>
          <ProviderId>3715</ProviderId>
        </ObjUrl>
      </IdUrlSet>
    </IdUrlList>
  </LinkSet>
</eLinkResult>
